name: built_mirrors_core
version: 0.10.5
description: generates `ClassMirror` from classes annotated with `@reflectable` or `@Reflectable()`
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/built_mirrors_core

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  source_gen: ^0.9.0
  build: ^1.0.1
  analyzer: ^0.36.0
