name: built_mirrors_core
version: 0.8.5
description: generates `ClassMirror` from classes annotated with `@reflectable` or `@Reflectable()`
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/built_mirrors_core

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  source_gen: ^0.8.0
  build: ^0.12.0
  analyzer: ^0.32.0
